"""Add monthly_fixed_expenses to User

Revision ID: aed8cab7c46d
Revises: 2f7c62d773d6
Create Date: 2026-02-05 03:06:33.026361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aed8cab7c46d'
down_revision: Union[str, None] = '2f7c62d773d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('monthly_fixed_expenses', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'monthly_fixed_expenses')
    # ### end Alembic commands ###
