"""Add current_quantity and average_price to Investment

Revision ID: e7bf03c682e8
Revises: f50e910a28ed
Create Date: 2026-02-05 02:48:06.064638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7bf03c682e8'
down_revision: Union[str, None] = 'f50e910a28ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment', sa.Column('current_quantity', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('investment', sa.Column('average_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment', 'average_price')
    op.drop_column('investment', 'current_quantity')
    # ### end Alembic commands ###
